source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.4'
# gem 'aws-sdk', '1.5.3'
gem 'aws-sdk', '1.6.3'
# gem 'aws-sdk-core'
gem 'multipart-post'
gem 'brightcove-api'
gem 'pg'
# gem 'mysql2'
