# note: brightcove write token is also in kaltura_to_brightcove.rb
# to find tokens in Brightcove, go to Account Settings > API Management

development:
  brightcove_write_token: 'secret'
  brightcove_read_token:  'secret'
  ajax_secret_key: 'hzsdLMiP4QZHnAoMwiNKQZD9J'

test:
  brightcove_write_token: 'C9gRFSOKF0rsirAqGPHdW-secret..'
  brightcove_read_token:  'C9gRFSOKF0rsirAqGPHdW-secret..'
  ajax_secret_key: 'hzsdLMiP4QZHnAoMwiNKQZD9J'

production:
  brightcove_write_token: 'C9gRFSOKF0rsirAqGPHdW-secret..'
  brightcove_read_token:  'C9gRFSOKF0rsirAqGPHdW-secret..'
  ajax_secret_key: 'hzsdLMiP4QZHnAoMwiNKQZD9J'



